# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [ALFRED-BOT, user2]
patreon: # Replace with a single Patreon ALFRED-BOT
open_collective: # Replace with a single Open Collective ALFRED-BOT
ko_fi: # Replace with a single Ko-fi ALFRED-MD
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay ALFRED-BOT
issuehunt: # Replace with a single IssueHunt ALFRED-BOT
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar ALFRED-BOT
buy_me_a_coffee: # Replace with a single Buy Me a Coffee ALFRED-BOT
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['+233596512099', 'link2']
